### ISSUE TITLE
Confirmation of N Magnitude in simulateAbsorptionSpectra.mlx

### ISSUE THREAD

**Issue by fwangwt** [LIFSim/LIFSim#1]
I am using simulateAbsorptionSpectra.mlx to simulate absorption spectra and would like to confirm the expected magnitude of the number density of the active species (N). According to the documentation, N should be provided in units of $m^{-3}$. However, when using this unit, I find that the calculated absorbance is about six orders of magnitude larger than results obtained from other sources, such as spectraplot.com.

I also noticed that the script imposes an upper limit on N, which is quite small compared to physically realistic values. I have manually removed this limitation in my tests.

When N is expressed in $cm^{-3}$ instead with the value , the absorbance values appear more reasonable. This makes me wonder whether I might be misunderstanding the expected unit convention or if there could be an unintended unit conversion issue in the script.

The following are the parameters I used to simulate NO absorption at 44412.9317 $cm^{-1}$. 
Laser parameters
`
unit = '1/cm';
startwn = 44412 ;
checkWnum(unit,startwn);
endwn = 44414;
checkWnum(unit,endwn);
step = 0.05;
dnuGL = 0.0001;
dnuLL = 0.00001;
`
Environment
`
T = 1550;
N = 703690852279406000000;
L = 0.05;
P = 2;
`
The number density N is calculated by:
$N = (2 * 101325 / 1.380649E-23 / 1550) * 0.01 * (108 * exp(-6.62607015E-34 * 540 * 29979245800 / 1.380649E-23 / 1550) / 8804.056156)$

Using the given parameters, simulateAbsorptionSpectra.mlx yields a maximum absorbance on the order of $10^5$. In contrast, a simulation using spectraplot.com with the ExoMol database under the same conditions (1550K, 2atm, $X_{NO}$=0.01, L=5cm) results in a maximum absorbance of approximately 0.5.

I've attached my simulateAbsorptionSpectra_NO.mlx script (renamed to .txt for uploading) and a .png result simulated on spectraplot.com for your reference. 

[simulateAbsorptionSpectra_NO.txt](https://github.com/user-attachments/files/18587861/simulateAbsorptionSpectra_NO.txt)

![Image](https://github.com/user-attachments/assets/c120f5a5-60b6-4510-a421-329ee60e6122)

![Image](https://github.com/user-attachments/assets/c72bd9f2-89f4-4a8b-a26e-2b86fc521477)

Could you help confirm whether N should indeed be in $m^{-3}$ and whether my approach to computing it is correct? Thank you for your time!

**Comment by abbaselmoussawi** [comment]
Thank you for the detailed report. The N calculation in your comment account for the Botlzmann factor, this factor is already in our calculations as f_ B in absorptionSpec.m. Nevertheless, we corrected the units of the overlap function according to Partridge and Normand, https://doi.org/10.1364/AO.34.002645. The correction was in overlap.m by normalizing  the laser and transition line shapes, then in the absorptionSpec.m by dividing the overlap over the total FWHM. Also, a division over speed of light was missing to obtain a dimensionless absorbance. Details are in the files (absorptionSpec.m and  overlap.m) of the latest commit https://github.com/LIFSim/LIFSim/commit/99ef173cdb7359c346f22cfe36963c1543fad6a4

The further discrepancies in the magnitude are likely owed to the line shape calculation namely the collisional broadening model and/or the laser line shape function (which we could not control in SpectraPlot). The collisional broadening in our tool can be influenced by collisional partners and their concentrations, the figures below resemble higher broadening when computed with our tool.  Those parameters and the databases are not the same for both our tool and SpectraPlot and a true 1:1 comparison is not possible. 

Examples settings: T = 1550 K, P = 2 bar, x=0.01 -->  N = px/(kT) ~ 9.4695e22 /m^3, FWHM Laser (1/cm): G=0.001, L=0.001 , step =  0.02, path = 0.05 m, ranges see on graph, for NO:
 
> LIFSim 4
> ![Image](https://github.com/user-attachments/assets/969928fb-29ab-4cbd-976c-9a2fbb3532bb)
> 
> SpectraPlot
> ![Image](https://github.com/user-attachments/assets/bd809e2b-7a57-4d67-9eda-e397bbe71827)

**Comment by fwangwt** [comment]
Thank you for carefully considering my issue. I understand that the results from LIFSim and SpectraPlot cannot be directly compared due to differences in the database and broadening calculations. However, based on the example settings you provided, as well as my repeated calculations using the latest release (99ef173), the computed absorbance still shows a three-order-of-magnitude difference in the integrated absorbance for the same transition between the two platforms—despite the fact that integrated absorbance is independent of broadening. This discrepancy is also evident in the peak absorbance values, which exhibit a similar magnitude difference, whereas the broadening applied by both platforms does not differ by orders of magnitude. Could you kindly further clarify this issue?

**Comment by abbaselmoussawi** [comment]
We revised this issue and this time used the Hydroxyl (OH), so we can rule out any database factor that might be influencing the calculation, because both LIFSim and SpectraPlot have the HITRAN line list for OH. Moreover, I used PGOPHER to have a benchmark, here we need to calculate the absorption cross section (absorbance / N / L ) to compare each of LIFSim and SpectraPlot to PGOPHER, see results below. 

Note: LIFSim is an open-source, for maximum transparency in our community. Thereby, we welcome you or others in the community to look in the source code, revise it, contribute and/or suggest corrections.

![Image](https://github.com/user-attachments/assets/7b669a8d-4639-4d63-94d2-7150bd471bd8)
